[auth]
site_url = "https://mercadodocompositor.com.br/"
additional_redirect_urls = [
  "http://localhost:3000/autenticacao",
  "http://localhost:3000/autenticacao?confirmado=1",
  "http://localhost:3000/autenticacao?modo=new-password",
  "http://localhost:3000/autenticacao?oauth=google",
  "https://mercadodocompositor.com.br/autenticacao",
  "https://mercadodocompositor.com.br/autenticacao?confirmado=1",
  "https://mercadodocompositor.com.br/autenticacao?modo=new-password",
  "https://mercadodocompositor.com.br/autenticacao?oauth=google"
]

[auth.email]
enable_confirmations = true
double_confirm_changes = true
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.rate_limit]
email_sent = 30

[functions.send-auth-email]
verify_jwt = false

[functions.validate-media-upload]
verify_jwt = true
